pipeline:
  build:
    image: olymk2/emacs-testing
    commands:
      - emacs -batch -l /drone/src/tests/.emacs.d/init.el -l ert-core.el -l ert-docker.el -l ert-compose.el -f ert-run-tests-batch-and-exit
