pipeline:
  build:
    image: jare/spacemacs:latest
    pull: true
    commands:
      - emacs -batch -f (package-install hydra) -l ert -l hydra -l docker-compose.el -f ert-run-tests-batch-and-exit
#/home/jare
